config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root to: "texts#index"

  resources :movies, only: [:index]
  resources :texts, only: [:index, :show] do
  resource  :readed_texts, only: [:create, :destroy]
  end

  resources :lines, only: [:index, :show]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line.rb
class Line < ApplicationRecord
  validates :genre, presence: true
  validates :title, presence: true
  validates :content, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :genre, :title, :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true
  validates :detail, presence: true
end

app/models/readed_text.rb
class ReadedText < ApplicationRecord
  belongs_to :user
  belongs_to :text
  validates :user_id, presence: true, uniqueness: {
    scope: :text_id,
    message: "は同じテキストを2回以上読破済みにできません"
  }
end

app/models/text.rb
class Text < ApplicationRecord
  has_many :readed_texts, dependent: :destroy
  # text.readed_users_list で text 読破済みユーザー一覧を取得
  has_many :readed_users_list, through: :readed_texts, source: :user

  validates :genre, presence: true
  validates :title, presence: true
  validates :content, presence: true

  # text を user が読破済みなら「true」, 未読なら「false」
  def readed_by?(user)
    readed_texts.find_by(user_id: user.id).present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :readed_texts, dependent: :destroy
  # user.readed_texts_list で text 読破済みテキスト一覧を取得
  has_many :readed_texts_list, through: :readed_texts, source: :text

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    @lines = Line.order(id: :asc)
  end

  def show
    @line = Line.find(params[:id])
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  PER_PAGE = 12

  def index
    if params[:genre].present?
      @movies = Movie.where(genre: params[:genre]).page(params[:page]).per(PER_PAGE)
    else
      @movies = Movie.where(genre: ["Basic", "Git", "HTML&CSS", "Ruby", "Ruby on Rails"]).page(params[:page]).per(PER_PAGE)
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order(id: :desc)
    @question = Question.new
  end

  def show
    @question = Question.all
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.create!(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :detail)
  end
end

app/controllers/readed_texts_controller.rb
class ReadedTextsController < ApplicationController
  def create
    @text_id = params[:text_id]
    current_user.readed_texts.create!(text_id: @text_id)
  end

  def destroy
    @text_id = params[:text_id]
    current_user.readed_texts.find_by(text_id: @text_id).destroy!
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  @@BASIC_GENRE = ["Basic", "Git", "Ruby", "Ruby on Rails"]

  def index
    params[:genre] ||= @@BASIC_GENRE
    @q = Text.where(genre: params[:genre]).ransack(params[:q])
    @texts = @q.result
  end

  def show
    @text = Text.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"
  require "coderay"

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      language = language.split(":")[0] if language.present?

      case language.to_s
      when "rb"
        lang = :ruby
      when "yml"
        lang = :yaml
      when "css"
        lang = :css
      when "html"
        lang = :html
      when ""
        lang = :md
      else
        lang = language
      end

      CodeRay.scan(code, lang).div
    end
  end

  def markdown(text)
    html_render = HTMLwithCoderay.new(
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: "nofollow", target: "_blank" },
    )
    options = {
      autolink: true,
      space_after_headers: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true,
      hard_wrap: true,
      xhtml: true,
      lax_html_blocks: true,
      strikethrough: true,
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text).html_safe
  end

  def line_color
    controller_name == "lines" ? "#28a745;" : "#5c99ff"
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <span class="navbar-brand">やんばるCODE</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav">
      <% if user_signed_in? %>

       <!-- ログイン時 -->
        <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Rails
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Ruby/Rails教材", texts_path, class: "dropdown-item" %>
              <%= link_to "動画教材", movies_path, class: "dropdown-item" %>
              <%= link_to "AWS講座", texts_path(genre: "AWS"), class: "dropdown-item" %>
              <%= link_to "プログラミング勉強会", "#", class: "dropdown-item" %>
              <%= link_to "質問集", "#", class: "dropdown-item" %>
            </div>
        </li>

        <li class="nav-item active">
          <%= link_to "対談", "#" , class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "情報発信", "#" , class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "動画編集講座", "#" , class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "ライティング講座", "#" , class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "マネタイズ講座", "#" , class: "nav-link" %>
        </li>

        <li class="nav-item dropdown active">
         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           PHP
         </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "PHPテキスト教材", texts_path(genre: "Php"), class: "dropdown-item" %>
            <%= link_to "PHP動画教材", "#", class: "dropdown-item" %>
          </div>
        </li>

        <li class="nav-item active">
         <%= link_to "LINE",  lines_path, class: "nav-link"%>
        </li>

        <li class="nav-item dropdown active">
         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         マイページ
         </a>
         <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "進捗管理", "#", class: "dropdown-item" %>
            <%= link_to "アカウント編集", edit_user_registration_path, class: "dropdown-item" %>
         </div>
        </li>

        <li class="nav-item active">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } , class: "nav-link" %>
        </li>

      <% else %>
          <!-- 非ログイン時 -->
          <li class="nav-item active">
            <%= link_to "ログイン", new_user_session_path , class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "新規登録", new_user_registration_path , class: "nav-link" %>
          </li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GyakutenCloneGroup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="fixed-top" style="background-color: <%= line_color %>">
      <%= render partial: "layouts/header" %>
    </header>
    <main>
      <div class="base-container">
        <%= render "layouts/flash" %>
        <div class="wrapper">
          <%= yield %>
        </div>
      </div>
    </main>
    <footer style="background-color: <%= line_color %>">
    </footer>
  </body>
</html>

app/views/lines/index.html.erb
<h1 id="line">LINE</h1>
<table class="table table-bordered table-striped mt-4">
  <thead class="line_table">
    <tr>
      <th class="w-1 align-middle">No.</th>
      <th class="w-2 align-middle">ジャンル</th>
      <th class="w-5 align-middle">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @lines.each.with_index(1) do |line, i| %>
      <tr>
        <th scope="row"><%= i %></th>
        <td class="break-word"><%= line.genre %></td>
        <td class="text-nowrap">
            <%= link_to line.title, line %>
            <% end %>
        </td>
      </tr>
  </tbody>
</table>

app/views/lines/show.html.erb
<div class="line_content">
  <div class="markdown">
    <%= markdown(@line.content) %>
  </div>
</div>

app/views/movies/index.html.erb
<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-12 col-md-6 col-lg-4">
      <div class="card border-dark mb-3">
        <div class="card-header embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="<%= movie.url %>"  allowfullscreen></iframe>
        </div>
        <div class="card-body card-size">
          <h5 class="card-title" style="font-size: 16px; padding-top: 10px;"><%= movie.title %> </h5>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="movie-paginate">
  <%= paginate(@movies) %>
</div>

app/views/questions/_form.html.erb
<%= form_with model: @question, local: true do |form| %>
<%# 質問 %>
  <div class="form-group">
    <%= form.label :title, "【質問】" %>
    <%= form.text_area :title, class: "form-control" %>
  </div>
<%# 詳細 %>
  <div class="form-group">
    <%= form.label :detail, "【詳細】" %>
    <%= form.text_area :detail, class: "form-control" %>
  </div>
<%# 送信 %>
  <div>
    <%= form.submit "送信", class: "btn btn-primary btn-block" %>
  </div>
  <% end %>

app/views/questions/edit.html.erb
<h2>編集</h2>
<%= render "form" %>

app/views/questions/index.html.erb
<h2>新規投稿</h2>
 <%= render "form" %>

 <table>
  <tbody>
    <% @questions.each.with_index(1) do |question, i| %>
      <tr>
        <td>
        <button type="button" class="btn btn-outline-light btn-lg btn-block"><%= link_to question.title, question %></button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table> 

app/views/questions/new.html.erb
<h2>新規投稿</h2>
<%= render "form" %>

app/views/questions/show.html.erb
<h2>投稿詳細</h2>
<p>【質問】<br> <%= @question.title %></p>
<p>【詳細】<br> <%= @question.detail %></p> 

app/views/readed_texts/create.js.erb
document.getElementById('readed-text-<%= @text_id %>').innerHTML = '<%= j render("texts/readed", text_id: @text_id) %>'

app/views/readed_texts/destroy.js.erb
document.getElementById('readed-text-<%= @text_id %>').innerHTML = '<%= j render("texts/unread", text_id: @text_id) %>'

app/views/texts/_readed.html.erb
<!-- 読破済み（クリックすると読破済みを解除する） -->
<object><%= link_to "読破済みを解除", text_readed_texts_path(text_id),
  method: :delete, remote: true, class: "btn btn-secondary btn-block" %></object>

app/views/texts/_unread.html.erb
<!-- 未読（クリックすると読破済みにする） -->
<object><%= link_to "読破済みにする", text_readed_texts_path(text_id),
  method: :post, remote: true, class: "btn btn-primary btn-block" %></object>

app/views/texts/index.html.erb
<div class="text-center">
  <h1>テキスト教材</h1>
</div>

<form class="text-search my-3 mx-auto">
  <%= search_form_for @q, url: root_path do |f| %>
    <%= f.search_field :title_cont, placeholder: "タイトル検索" %>
    <%= f.search_field :genre_cont, placeholder: "ジャンル検索" %>
    <%= f.submit "検索" %>
  <% end %>
</form>

<div class="row">
  <% @texts.each do |text| %>
    <div class="col-12 col-md-6 col-lg-4 text-card-container">
      <div class="card content-card border-dark mb-3">
        <%= link_to text_path(text), target: :_blank do %>
          <div class="card-header p-0">
            <%= image_tag "no_image.jpg", loading: "lazy", alt: text.title, class: "img-fluid" %>
          </div>
          <div class="card-body text-dark text-card-body">
            <div id="readed-text-<%= text.id %>">
              <% if text.readed_by?(current_user) %>
                <%= render "readed", text_id: text.id %>
              <% else %>
                <%= render "unread", text_id: text.id %>
              <% end %>
            </div>
            <p class="text-title"><%= text.title %></p>
            <p class="text-subtitle">【<%= text.genre %>】</p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/texts/show.html.erb
<section id="text-contents">
  <h2><%= markdown(@text.title) %></h2>
  <div class="markdown">
    <%= markdown(@text.content) %>
  </div>
</section>